#pragma once

/* GEN */
#include "rigdeps/rig_noext_types.h"
#include "rigdeps/rig_math.h"


RigVAO* rig_vao_create(RigGPUCtx *gpu, uint32_t vbo_id, uint32_t ibo_id, const RigVertexAttrib *attribs, uint8_t n_attribs, uint32_t n_vertices, uint32_t n_indices);
bool rig_gpu_make_current(RigGPUCtx *gpu);
bool rig_gpu_make_current__rig_variant_ed4ba848(RigGPUCtx *gpu);
const RigMatEntry* rig_mat_find(const char *name);
const char* rig_glsl_src(const char *name);
int rig_gpu_init(RigGPUCtx *gpu, void *native_display, void *native_window, bool offscreen);
int rig_gpu_init__rig_variant_8fed6a43(RigGPUCtx *gpu, void *native_display, void *native_window, bool offscreen);
int rig_gpu_uniform_loc(uint32_t prog, const char *name);
int rig_mat_set(RigGPUCtx *gpu, uint32_t prog, const char *name);
int rig_pbr_pipeline_init(RigGPUCtx *gpu, RigPBRPipeline *pbr, uint32_t w, uint32_t h);
int rig_pbr_pipeline_init__rig_variant_a1fd90e3(RigGPUCtx *gpu, RigPBRPipeline *pbr, uint32_t w, uint32_t h);
uint32_t rig_buffer_create(RigGPUCtx *gpu, RigBufType type, const void *data, size_t size, RigBufUsage usage);
uint32_t rig_buffer_create__rig_variant_91d1085b(RigGPUCtx *gpu, RigBufType type, const void *data, size_t size, RigBufUsage usage);
uint32_t rig_fbo_create(RigGPUCtx *gpu, uint32_t w, uint32_t h, RigTexFormat color_fmt, bool with_depth);
uint32_t rig_fbo_create__rig_variant_8f08aafd(RigGPUCtx *gpu, uint32_t w, uint32_t h, RigTexFormat color_fmt, bool with_depth);
uint32_t rig_fbo_create_msaa(RigGPUCtx *gpu, uint32_t w, uint32_t h, uint8_t samples);
uint32_t rig_fbo_create_msaa__rig_variant_352471dc(RigGPUCtx *gpu, uint32_t w, uint32_t h, uint8_t samples);
uint32_t rig_gpu_compile_shader(RigShaderStage stage, const char *src);
uint32_t rig_gpu_create_vao(void);
uint32_t rig_gpu_create_vbo(const void *data, size_t size);
uint32_t rig_gpu_link_program(uint32_t vs, uint32_t fs);
uint32_t rig_program_link(RigGPUCtx *gpu, uint32_t vert_id, uint32_t frag_id);
uint32_t rig_program_link__rig_variant_4dec1879(RigGPUCtx *gpu, uint32_t vert_id, uint32_t frag_id);
uint32_t rig_program_link_compute(RigGPUCtx *gpu, uint32_t comp_id);
uint32_t rig_program_link_compute__rig_variant_eaffd9f3(RigGPUCtx *gpu, uint32_t comp_id);
uint32_t rig_shader_compile(RigGPUCtx *gpu, RigShaderStage stage, const char *src, const char *debug_name);
uint32_t rig_shader_compile__rig_variant_9ccd03ad(RigGPUCtx *gpu, RigShaderStage stage, const char *src, const char *debug_name);
uint32_t rig_texture_create(RigGPUCtx *gpu, RigTexFormat fmt, uint32_t w, uint32_t h, const void *data, bool gen_mips);
uint32_t rig_texture_create__rig_variant_5c7ac5a7(RigGPUCtx *gpu, RigTexFormat fmt, uint32_t w, uint32_t h, const void *data, bool gen_mips);
uint32_t rig_texture_create_cubemap(RigGPUCtx *gpu, RigTexFormat fmt, uint32_t size, const void *faces[6]);
uint32_t rig_texture_create_cubemap__rig_variant_f821a64d(RigGPUCtx *gpu, RigTexFormat fmt, uint32_t size, const void *faces[6]);
void rig_buffer_bind(RigGPUCtx *gpu, uint32_t buf_id, uint32_t slot);
void rig_buffer_bind__rig_variant_486e6140(RigGPUCtx *gpu, uint32_t buf_id, uint32_t slot);
void rig_buffer_free(RigGPUCtx *gpu, uint32_t buf_id);
void rig_buffer_free__rig_variant_1d577ecd(RigGPUCtx *gpu, uint32_t buf_id);
void rig_buffer_update(RigGPUCtx *gpu, uint32_t buf_id, const void *data, size_t size, size_t offset);
void rig_buffer_update__rig_variant_a187d868(RigGPUCtx *gpu, uint32_t buf_id, const void *data, size_t size, size_t offset);
void rig_draw_arrays(RigGPUCtx *gpu, uint32_t mode, uint32_t first, uint32_t count);
void rig_draw_arrays__rig_variant_ab61e1db(RigGPUCtx *gpu, uint32_t mode, uint32_t first, uint32_t count);
void rig_draw_indexed(RigGPUCtx *gpu, RigVAO *vao, uint32_t offset, uint32_t count);
void rig_draw_indexed__rig_variant_69255d7a(RigGPUCtx *gpu, RigVAO *vao, uint32_t offset, uint32_t count);
void rig_draw_screen_quad(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_draw_screen_quad__rig_variant_8c3d6ccd(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_fbo_bind(RigGPUCtx *gpu, uint32_t fbo_id);
void rig_fbo_bind__rig_variant_6606cf4a(RigGPUCtx *gpu, uint32_t fbo_id);
void rig_fbo_blit(RigGPUCtx *gpu, uint32_t src, uint32_t dst, uint32_t w, uint32_t h, bool color, bool depth);
void rig_fbo_blit__rig_variant_7640e874(RigGPUCtx *gpu, uint32_t src, uint32_t dst, uint32_t w, uint32_t h, bool color, bool depth);
void rig_fbo_free(RigGPUCtx *gpu, uint32_t fbo_id);
void rig_fbo_free__rig_variant_0c5d7480(RigGPUCtx *gpu, uint32_t fbo_id);
void rig_fbo_unbind(RigGPUCtx *gpu);
void rig_fbo_unbind__rig_variant_2f18cd10(RigGPUCtx *gpu);
void rig_gpu_bind_vao(uint32_t vao_id);
void rig_gpu_delete_shader(uint32_t id);
void rig_gpu_destroy(RigGPUCtx *gpu);
void rig_gpu_destroy__rig_variant_ce2587a6(RigGPUCtx *gpu);
void rig_gpu_detect_caps(RigGPUCtx *gpu);
void rig_gpu_detect_caps__rig_variant_bf99f70c(RigGPUCtx *gpu);
void rig_gpu_draw_triangles(uint32_t first, uint32_t count);
void rig_gpu_frame_begin(RigGPUCtx *gpu);
void rig_gpu_frame_begin__rig_variant_38c25b08(RigGPUCtx *gpu);
void rig_gpu_present(RigGPUCtx *gpu);
void rig_gpu_present__rig_variant_21198354(RigGPUCtx *gpu);
void rig_gpu_print_caps(const RigGPUCtx *gpu);
void rig_gpu_print_caps__rig_variant_42647ddb(const RigGPUCtx *gpu);
void rig_gpu_release_thread(RigGPUCtx *gpu);
void rig_gpu_release_thread__rig_variant_d58e0b7b(RigGPUCtx *gpu);
void rig_gpu_uniform_1f(int loc, float v);
void rig_gpu_uniform_2f(int loc, float a, float b);
void rig_gpu_uniform_4f(int loc, float a, float b, float c, float d);
void rig_gpu_use_program(uint32_t prog);
void rig_gpu_vao_attrib(uint32_t vao_id, uint32_t vbo_id, uint32_t idx, uint32_t nc, uint32_t stride, uint32_t offset);
void rig_mat_apply(RigGPUCtx *gpu, uint32_t prog, const RigMatEntry *e);
void rig_pbr_begin_geometry(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_begin_geometry__rig_variant_382ce2b6(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_bloom_pass(RigGPUCtx *gpu, RigPBRPipeline *pbr, float threshold, float strength);
void rig_pbr_bloom_pass__rig_variant_427e44ff(RigGPUCtx *gpu, RigPBRPipeline *pbr, float threshold, float strength);
void rig_pbr_end_geometry(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_end_geometry__rig_variant_fa079a7a(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_lighting_pass(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_lighting_pass__rig_variant_2162bc86(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_pipeline_destroy(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_pipeline_destroy__rig_variant_2acb32d1(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_pipeline_resize(RigGPUCtx *gpu, RigPBRPipeline *pbr, uint32_t w, uint32_t h);
void rig_pbr_pipeline_resize__rig_dup_85b654a6(RigGPUCtx *gpu, RigPBRPipeline *pbr, uint32_t w, uint32_t h);
void rig_pbr_ssao_pass(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_ssao_pass__rig_variant_e821b55e(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_sss_pass(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_sss_pass__rig_variant_0db493a8(RigGPUCtx *gpu, RigPBRPipeline *pbr);
void rig_pbr_tonemap_pass(RigGPUCtx *gpu, RigPBRPipeline *pbr, float exposure);
void rig_pbr_tonemap_pass__rig_variant_efa45d27(RigGPUCtx *gpu, RigPBRPipeline *pbr, float exposure);
void rig_program_bind(RigGPUCtx *gpu, uint32_t prog_id);
void rig_program_bind__rig_variant_16192561(RigGPUCtx *gpu, uint32_t prog_id);
void rig_program_free(RigGPUCtx *gpu, uint32_t id);
void rig_program_free__rig_variant_4af384b7(RigGPUCtx *gpu, uint32_t id);
void rig_shader_free(RigGPUCtx *gpu, uint32_t id);
void rig_shader_free__rig_variant_2a355747(RigGPUCtx *gpu, uint32_t id);
void rig_state_blend(RigGPUCtx *gpu, bool enable, uint32_t src, uint32_t dst);
void rig_state_blend__rig_variant_3d652f9d(RigGPUCtx *gpu, bool enable, uint32_t src, uint32_t dst);
void rig_state_clear(RigGPUCtx *gpu, float r, float g, float b, float a, float depth);
void rig_state_clear__rig_variant_f239e16c(RigGPUCtx *gpu, float r, float g, float b, float a, float depth);
void rig_state_cull(RigGPUCtx *gpu, bool enable, uint32_t mode);
void rig_state_cull__rig_variant_d3fee156(RigGPUCtx *gpu, bool enable, uint32_t mode);
void rig_state_default(RigGPUCtx *gpu);
void rig_state_default__rig_variant_c2df75b5(RigGPUCtx *gpu);
void rig_state_depth(RigGPUCtx *gpu, bool test, bool write, uint32_t func);
void rig_state_depth__rig_variant_0afda971(RigGPUCtx *gpu, bool test, bool write, uint32_t func);
void rig_state_viewport(RigGPUCtx *gpu, uint32_t x, uint32_t y, uint32_t w, uint32_t h);
void rig_state_viewport__rig_variant_64044d00(RigGPUCtx *gpu, uint32_t x, uint32_t y, uint32_t w, uint32_t h);
void rig_texture_bind(RigGPUCtx *gpu, uint32_t tex_id, uint32_t slot);
void rig_texture_bind__rig_variant_d8a658e0(RigGPUCtx *gpu, uint32_t tex_id, uint32_t slot);
void rig_texture_free(RigGPUCtx *gpu, uint32_t tex_id);
void rig_texture_free__rig_variant_3cd213ca(RigGPUCtx *gpu, uint32_t tex_id);
void rig_uniform_1f(RigGPUCtx *gpu, uint32_t prog, const char *name, float v);
void rig_uniform_1f__rig_variant_139a6141(RigGPUCtx *g, uint32_t p, const char *n, float v);
void rig_uniform_1i(RigGPUCtx *gpu, uint32_t prog, const char *name, int v);
void rig_uniform_1i__rig_variant_b6f38c1e(RigGPUCtx *g, uint32_t p, const char *n, int v);
void rig_uniform_2f(RigGPUCtx *gpu, uint32_t prog, const char *name, float x, float y);
void rig_uniform_2f__rig_variant_2a838c41(RigGPUCtx *g, uint32_t p, const char *n, float x, float y);
void rig_uniform_3f(RigGPUCtx *gpu, uint32_t prog, const char *name, float x, float y, float z);
void rig_uniform_3f__rig_variant_6358b329(RigGPUCtx *g, uint32_t p, const char *n, float x, float y, float z);
void rig_uniform_4f(RigGPUCtx *gpu, uint32_t prog, const char *name, float x, float y, float z, float w);
void rig_uniform_4f__rig_variant_dc6a1f46(RigGPUCtx *g, uint32_t p, const char *n, float x, float y, float z, float w);
void rig_uniform_mat4(RigGPUCtx *gpu, uint32_t prog, const char *name, const float *m16);
void rig_uniform_mat4__rig_variant_97562df5(RigGPUCtx *g, uint32_t p, const char *n, const float *m);
void rig_vao_bind(RigGPUCtx *gpu, RigVAO *vao);
void rig_vao_bind__rig_variant_e93c3290(RigGPUCtx *gpu, RigVAO *vao);
void rig_vao_free(RigGPUCtx *gpu, RigVAO *vao);
void rig_vao_free__rig_variant_432b2aec(RigGPUCtx *gpu, RigVAO *vao);
