/*
 * rig_face_ng_skin.c — RigCom v24 NEXT GENERATION · Sistema de Piel Ultra-Detallado
 * ══════════════════════════════════════════════════════════════════════════════════
 * Richard Felipe Urbina · RIGCOM Ecosystem · Arquitecto Soberano
 *
 * MODELO BIOFÍSICO COMPLETO:
 *   8 capas de SSS espectral (Donner-Jensen 2005 + Chiang 2016 modificado)
 *   Absorción cromofórica real (melanina, hemoglobina, bilirrubina, caroteno)
 *   Poros sebáceos con interreflexión difusa (Voronoi + normal displacement)
 *   Red vascular simulada con pulsación cardíaca
 *   Glándulas sudoríparas con propagación de humedad
 *   Arrugas dinámicas controladas por pesos FACS en tiempo real
 *   Pelo velloso (vello facial) con modelo de fibra corta
 *   Queratina superficial con Fresnel IOR=1.55 (estrato córneo)
 *   Dermis con fibras de colágeno anisotrópicas
 *
 * φ = 1.6180339887498948482
 * Schumann = 7.83 Hz
 */

/* [SOBERANO] rigdeps/rig_std_base.h eliminado — cubierto por stack noext */
#include "rig_face_ng.h"
#include "rig_noext_mem.h"
#include "rig_noext_str.h"
#include "rig_math.h"
#include "rig_noext_io.h"
#include "../include/riglib_math.h"

#define NG_PHI          1.6180339887498948482f
#define NG_PHI_INV      0.6180339887498948482f
#define NG_SCHUMANN     7.83f
#define NG_PI           3.14159265358979323846f
#define NG_TAU          6.28318530717958647692f
#define NG_SQRT2        1.41421356237309504880f
#define NG_E            2.71828182845904523536f

#define SKIN_BUF  (256 * 1024)   /* 256 KB por shader */
#define JS_BUF    (128 * 1024)   /* 128 KB por runtime JS */
#define FA(b,s,p,...) do { \
    if ((p)<(int)(s)) { int _n=rl_snprintf((b)+(p),(s)-(p),__VA_ARGS__); \
    if(_n>0)(p)+=_n; } } while(0)

/* ═══════════════════════════════════════════════════════════════
 * GLSL CABECERA SOBERANA — versión NG con todas las constantes
 * ═══════════════════════════════════════════════════════════════ */
static const char *NG_GLSL_HEADER =
    "#version 300 es\n"
    "precision highp float;\n"
    "precision highp int;\n"
    "precision highp sampler2D;\n\n"
    "/* ── Constantes φ-soberanas ───────────────────────────────── */\n"
    "const float PHI        = 1.6180339887;\n"
    "const float PHI_INV    = 0.6180339887;\n"
    "const float PHI2       = 2.6180339887;  /* φ² = φ+1 */\n"
    "const float PHI_INV2   = 0.3819660113;  /* φ⁻² = 1-φ⁻¹ */\n"
    "const float PI         = 3.14159265359;\n"
    "const float TAU        = 6.28318530718;\n"
    "const float INV_PI     = 0.31830988618;\n"
    "const float INV_TAU    = 0.15915494309;\n"
    "const float SQRT2      = 1.41421356237;\n"
    "const float SQRT3      = 1.73205080757;\n"
    "const float SCHUMANN   = 7.83;          /* Hz — Resonancia Schumann */\n"
    "const float E_BASE     = 2.71828182846;\n\n"
    "/* ── Constantes biofísicas de piel ───────────────────────── */\n"
    "const float IOR_CORNEUM   = 1.55;  /* estrato córneo */\n"
    "const float IOR_EPIDERMIS = 1.43;  /* epidermis */\n"
    "const float IOR_DERMIS    = 1.38;  /* dermis */\n"
    "const float IOR_AIR       = 1.00;\n"
    "const float SKIN_G        = 0.90;  /* factor de anisotropía de Henyey-Greenstein */\n\n";

/* ═══════════════════════════════════════════════════════════════
 * GLSL — RUIDO, HASH, FBM — librería completa de procedurales
 * ═══════════════════════════════════════════════════════════════ */
static const char *NG_GLSL_PROCEDURAL =
    "/* ══════════════════════════════════════════════════════════ */\n"
    "/* LIBRERÍA DE RUIDO PROCEDURAL SOBERANA                      */\n"
    "/* ══════════════════════════════════════════════════════════ */\n\n"
    "/* Hash sin seno — Jarzynski & Harsh 2016 */\n"
    "float hash11(float p) {\n"
    "    p = fract(p * .1031);\n"
    "    p *= p + 33.33;\n"
    "    return fract(p * (p + p));\n"
    "}\n"
    "float hash12(vec2 p) {\n"
    "    vec3 p3 = fract(vec3(p.xyx) * .1031);\n"
    "    p3 += dot(p3, p3.yzx + 33.33);\n"
    "    return fract((p3.x + p3.y) * p3.z);\n"
    "}\n"
    "float hash13(vec3 p) {\n"
    "    p = fract(p * .1031);\n"
    "    p += dot(p, p.zyx + 31.32);\n"
    "    return fract((p.x + p.y) * p.z);\n"
    "}\n"
    "vec2 hash22(vec2 p) {\n"
    "    vec3 p3 = fract(vec3(p.xyx) * vec3(.1031,.1030,.0973));\n"
    "    p3 += dot(p3, p3.yzx + 33.33);\n"
    "    return fract((p3.xx + p3.yz) * p3.zy);\n"
    "}\n"
    "vec3 hash33(vec3 p3) {\n"
    "    p3 = fract(p3 * vec3(.1031,.1030,.0973));\n"
    "    p3 += dot(p3, p3.yxz + 33.33);\n"
    "    return fract((p3.xxy + p3.yxx) * p3.zyx);\n"
    "}\n\n"
    "/* Value noise suave 2D */\n"
    "float vnoise2(vec2 p) {\n"
    "    vec2 i = floor(p);\n"
    "    vec2 f = fract(p);\n"
    "    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0); /* quintic */\n"
    "    return mix(mix(hash12(i + vec2(0,0)), hash12(i + vec2(1,0)), u.x),\n"
    "               mix(hash12(i + vec2(0,1)), hash12(i + vec2(1,1)), u.x), u.y);\n"
    "}\n"
    "/* Value noise suave 3D */\n"
    "float vnoise3(vec3 p) {\n"
    "    vec3 i = floor(p); vec3 f = fract(p);\n"
    "    vec3 u = f*f*f*(f*(f*6.-15.)+10.);\n"
    "    return mix(mix(mix(hash13(i),           hash13(i+vec3(1,0,0)),u.x),\n"
    "                   mix(hash13(i+vec3(0,1,0)),hash13(i+vec3(1,1,0)),u.x),u.y),\n"
    "               mix(mix(hash13(i+vec3(0,0,1)),hash13(i+vec3(1,0,1)),u.x),\n"
    "                   mix(hash13(i+vec3(0,1,1)),hash13(i+vec3(1,1,1)),u.x),u.y),u.z);\n"
    "}\n\n"
    "/* Gradient noise 3D (Perlin) */\n"
    "float gnoise3(vec3 p) {\n"
    "    vec3 i = floor(p); vec3 f = fract(p);\n"
    "    vec3 u = f*f*(3.-2.*f);\n"
    "    vec3 g000=hash33(i)-0.5,       g100=hash33(i+vec3(1,0,0))-0.5;\n"
    "    vec3 g010=hash33(i+vec3(0,1,0))-0.5, g110=hash33(i+vec3(1,1,0))-0.5;\n"
    "    vec3 g001=hash33(i+vec3(0,0,1))-0.5, g101=hash33(i+vec3(1,0,1))-0.5;\n"
    "    vec3 g011=hash33(i+vec3(0,1,1))-0.5, g111=hash33(i+vec3(1,1,1))-0.5;\n"
    "    float v000=dot(g000,f),           v100=dot(g100,f-vec3(1,0,0));\n"
    "    float v010=dot(g010,f-vec3(0,1,0)),v110=dot(g110,f-vec3(1,1,0));\n"
    "    float v001=dot(g001,f-vec3(0,0,1)),v101=dot(g101,f-vec3(1,0,1));\n"
    "    float v011=dot(g011,f-vec3(0,1,1)),v111=dot(g111,f-vec3(1,1,1));\n"
    "    return mix(mix(mix(v000,v100,u.x),mix(v010,v110,u.x),u.y),\n"
    "               mix(mix(v001,v101,u.x),mix(v011,v111,u.x),u.y),u.z);\n"
    "}\n\n"
    "/* fBm — fractal Brownian motion, hasta 8 octavas */\n"
    "float fbm(vec3 p, int oct, float lacunarity, float gain) {\n"
    "    float v=0., a=0.5;\n"
    "    mat3 rot = mat3(0.8,-0.6,0., 0.6,0.8,0., 0.,0.,1.);\n"
    "    for(int i=0;i<8;i++) {\n"
    "        if(i>=oct) break;\n"
    "        v += a * vnoise3(p);\n"
    "        p = rot * p * lacunarity;\n"
    "        a *= gain;\n"
    "    }\n"
    "    return v;\n"
    "}\n\n"
    "/* Ruido φ-quasi-periódico — distribucion de Fibonacci */\n"
    "float phi_noise(vec3 p) {\n"
    "    float n = p.x*PHI + p.y*PHI*PHI + p.z*PHI*PHI*PHI;\n"
    "    return fract(sin(n*127.1+12.9898)*43758.5453);\n"
    "}\n\n"
    "/* Voronoi F1 + F2 — celdas */\n"
    "vec3 voronoi(vec3 p) {\n"
    "    vec3 b = floor(p);\n"
    "    vec3 f = fract(p);\n"
    "    float F1 = 8., F2 = 8.;\n"
    "    vec3 cell1 = vec3(0.);\n"
    "    for(int k=-1;k<=1;k++) for(int j=-1;j<=1;j++) for(int i=-1;i<=1;i++) {\n"
    "        vec3 n = vec3(float(i),float(j),float(k));\n"
    "        vec3 c = hash33(b+n) + n;\n"
    "        float d = length(f - c);\n"
    "        if(d < F1) { F2=F1; F1=d; cell1=b+n; }\n"
    "        else if(d < F2) F2=d;\n"
    "    }\n"
    "    return vec3(F1, F2, hash13(cell1));\n"
    "}\n\n"
    "/* Curl noise 3D — para fluidos/vapor/sudor */\n"
    "vec3 curl_noise(vec3 p) {\n"
    "    const float e = 0.01;\n"
    "    float nx0=vnoise3(p+vec3(0,e,0)), nx1=vnoise3(p-vec3(0,e,0));\n"
    "    float ny0=vnoise3(p+vec3(0,0,e)), ny1=vnoise3(p-vec3(0,0,e));\n"
    "    float nz0=vnoise3(p+vec3(e,0,0)), nz1=vnoise3(p-vec3(e,0,0));\n"
    "    float a0=vnoise3(p+vec3(0,e,0)), a1=vnoise3(p+vec3(0,0,e));\n"
    "    float b0=vnoise3(p+vec3(0,0,e)), b1=vnoise3(p+vec3(e,0,0));\n"
    "    float c0=vnoise3(p+vec3(e,0,0)), c1=vnoise3(p+vec3(0,e,0));\n"
    "    return normalize(vec3(\n"
    "        (nx0-nx1)-(a0-a1),\n"
    "        (ny0-ny1)-(b0-b1),\n"
    "        (nz0-nz1)-(c0-c1)) * (0.5/e));\n"
    "}\n\n";

/* ═══════════════════════════════════════════════════════════════
 * GLSL — PBR + SSS + ESPECTRAL — corazón del shader NG
 * ═══════════════════════════════════════════════════════════════ */
static const char *NG_GLSL_PBR_SSS =
    "/* ══════════════════════════════════════════════════════════ */\n"
    "/* PBR COOK-TORRANCE COMPLETO + SSS ESPECTRAL 8 CAPAS         */\n"
    "/* ══════════════════════════════════════════════════════════ */\n\n"
    "/* Fresnel Schlick con F82 (Naty Hoffman 2016) */\n"
    "vec3 F_Schlick(float cosTheta, vec3 F0, vec3 F82) {\n"
    "    float x = 1.0 - cosTheta;\n"
    "    float x2 = x*x; float x5 = x2*x2*x;\n"
    "    /* Interpolación cúbica entre F0 y valor a 82° */\n"
    "    vec3 F = F0 + (F82 - F0) * max(0., 1.0 - 7.0*cosTheta) * x5 * x2;\n"
    "    return clamp(F0 + (1.0 - F0)*x5, vec3(0.), vec3(1.));\n"
    "}\n\n"
    "/* GGX NDF — Trowbridge-Reitz con clamp numérico */\n"
    "float D_GGX(float NdH, float alpha) {\n"
    "    float a2 = alpha * alpha;\n"
    "    float d  = NdH * NdH * (a2 - 1.0) + 1.0;\n"
    "    return a2 / max(PI * d * d, 1e-7);\n"
    "}\n\n"
    "/* GGX NDF anisótropo — para pelo/fibra de colágeno */\n"
    "float D_GGX_aniso(float NdH, float TdH, float BdH,\n"
    "                   float ax, float ay) {\n"
    "    float d = TdH*TdH/(ax*ax) + BdH*BdH/(ay*ay) + NdH*NdH;\n"
    "    return 1.0 / max(PI * ax * ay * d * d, 1e-7);\n"
    "}\n\n"
    "/* Geometría Schlick-GGX + Smith */\n"
    "float G_SchlickGGX(float NdV, float alpha) {\n"
    "    float k = (alpha + 1.0) * (alpha + 1.0) * 0.125;\n"
    "    return NdV / max(NdV*(1.0 - k) + k, 1e-7);\n"
    "}\n"
    "float G_Smith(float NdV, float NdL, float alpha) {\n"
    "    return G_SchlickGGX(NdV,alpha) * G_SchlickGGX(NdL,alpha);\n"
    "}\n\n"
    "/* ACES Filmic tone mapping — Hill/Narkowicz */\n"
    "vec3 ACES_tonemap(vec3 x) {\n"
    "    const float a=2.51, b=0.03, c=2.43, d=0.59, e=0.14;\n"
    "    return clamp((x*(a*x+b))/(x*(c*x+d)+e), 0.0, 1.0);\n"
    "}\n\n"
    "/* Neutral tone map (Khronos) */\n"
    "vec3 neutral_tonemap(vec3 c) {\n"
    "    float peak = max(max(c.r,c.g),c.b);\n"
    "    vec3  ratio= c / max(peak, 1e-7);\n"
    "    float compressor = peak / (0.18 + peak);\n"
    "    return ratio * compressor;\n"
    "}\n\n"
    "/* ── SSS 8 CAPAS ESPECTRAL ── */\n"
    "/* Modelo físico de dispersión de luz en piel humana\n"
    " * Referencia: Donner & Jensen 2005 — «Light Diffusion in Multi-Layered Translucent Materials»\n"
    " * Modificado para tiempo real con aproximación exponencial doble\n"
    " *\n"
    " * Capas (exterior → interior):\n"
    " *  0: Película sebácea     (ε = 0.002 mm)  IOR=1.48\n"
    " *  1: Estrato córneo       (ε = 0.015 mm)  IOR=1.55\n"
    " *  2: Estrato granuloso    (ε = 0.020 mm)  IOR=1.50\n"
    " *  3: Estrato espinoso     (ε = 0.030 mm)  IOR=1.43\n"
    " *  4: Estrato basal        (ε = 0.050 mm)  IOR=1.44  ← melanocitos\n"
    " *  5: Dermis papilar       (ε = 0.200 mm)  IOR=1.38  ← vasos papilares\n"
    " *  6: Dermis reticular     (ε = 1.000 mm)  IOR=1.38  ← colágeno+elastina\n"
    " *  7: Hipodermis           (ε = 3.000 mm)  IOR=1.44  ← tejido adiposo\n"
    " */\n"
    "vec3 sss_8layer(\n"
    "    vec3  albedo,\n"
    "    float thickness,        /* mapa de espesor 0-1 → 0-4mm */\n"
    "    float melanin_eu,       /* 0-1: eumelanina (negro-marrón) */\n"
    "    float melanin_ph,       /* 0-1: feomelanina (rojo-amarillo) */\n"
    "    float hemoglobin_oxy,   /* 0-1: oxihemoglobina (rojo) */\n"
    "    float hemoglobin_deoxy, /* 0-1: deoxihemoglobina (azul-morado) */\n"
    "    float bilirubin,        /* 0-1: bilirrubina (amarillo) */\n"
    "    float carotene,         /* 0-1: caroteno (naranja) */\n"
    "    float age               /* 0-1: envejecimiento */\n"
    ") {\n"
    "    /* Coeficientes de absorción por cromóforo (mm⁻¹) aproximados RGB */\n"
    "    /* Melanina eumelanina: absorbe todo, máximo en UV/azul */\n"
    "    vec3 mu_a_eu  = vec3(0.018, 0.013, 0.006) * melanin_eu * 12.0;\n"
    "    /* Feomelanina: rojo-amarillo */\n"
    "    vec3 mu_a_ph  = vec3(0.004, 0.008, 0.016) * melanin_ph * 4.0;\n"
    "    /* Oxihemoglobina: pico a 542nm y 577nm */\n"
    "    vec3 mu_a_Hbo = vec3(0.022, 0.008, 0.003) * hemoglobin_oxy * 8.0;\n"
    "    /* Deoxihemoglobina: pico a 555nm y 760nm */\n"
    "    vec3 mu_a_Hbd = vec3(0.008, 0.016, 0.025) * hemoglobin_deoxy * 6.0;\n"
    "    /* Bilirrubina: máximo ~460nm (amarillo-naranja) */\n"
    "    vec3 mu_a_bil = vec3(0.020, 0.010, 0.000) * bilirubin * 3.0;\n"
    "    /* Caroteno: máximo ~450nm */\n"
    "    vec3 mu_a_car = vec3(0.015, 0.008, 0.000) * carotene * 2.0;\n\n"
    "    /* Absorción total combinada */\n"
    "    vec3 mu_a = mu_a_eu + mu_a_ph + mu_a_Hbo + mu_a_Hbd + mu_a_bil + mu_a_car;\n"
    "    mu_a = max(mu_a, vec3(0.001));\n\n"
    "    /* Coeficiente de dispersión reducido de cada capa (mm⁻¹) */\n"
    "    /* μs' = μs*(1-g), g=0.9 anisotropía */\n"
    "    float sc = 1.0 + age * 0.5;\n"
    "    vec3 ms_oil   = vec3(1.2,  1.8,  2.2)  * sc;\n"
    "    vec3 ms_corn  = vec3(2.5,  3.2,  4.0)  * sc;\n"
    "    vec3 ms_gran  = vec3(2.0,  2.8,  3.5)  * sc;\n"
    "    vec3 ms_spin  = vec3(1.8,  2.5,  3.2)  * sc;\n"
    "    vec3 ms_basal = vec3(1.5,  2.0,  2.8)  * sc;\n"
    "    vec3 ms_dpap  = vec3(0.8,  1.2,  1.6)  * sc;\n"
    "    vec3 ms_dret  = vec3(0.5,  0.8,  1.1)  * sc;\n"
    "    vec3 ms_hyp   = vec3(0.3,  0.4,  0.5)  * sc;\n\n"
    "    /* Profundidad física (mm) en función del mapa de espesor */\n"
    "    float depth_mm = thickness * 4.0;  /* 0-4 mm */\n\n"
    "    /* Perfil de difusión doble exponencial por capa */\n"
    "    /* L_layer = albedo * exp(-mu_eff * depth) */\n"
    "    /* mu_eff  = sqrt(3 * mu_a * (mu_a + mu_s')) */\n"
    "    #define SSS_LAYER(d, mu_s, w) \\\n"
    "        (albedo * exp(-(sqrt(3.0*mu_a*(mu_a+mu_s))*d)) * (w))\n\n"
    "    vec3 L = vec3(0.);\n"
    "    float d = depth_mm;\n"
    "    L += SSS_LAYER(min(d, 0.002), ms_oil,   0.02);\n"
    "    L += SSS_LAYER(min(d, 0.017), ms_corn,  0.08);\n"
    "    L += SSS_LAYER(min(d, 0.037), ms_gran,  0.08);\n"
    "    L += SSS_LAYER(min(d, 0.067), ms_spin,  0.10);\n"
    "    L += SSS_LAYER(min(d, 0.117), ms_basal, 0.12);\n"
    "    L += SSS_LAYER(min(d, 0.317), ms_dpap,  0.20);\n"
    "    L += SSS_LAYER(min(d, 1.317), ms_dret,  0.25);\n"
    "    L += SSS_LAYER(    d,         ms_hyp,   0.15);\n"
    "    #undef SSS_LAYER\n\n"
    "    /* Componente de retro-dispersión (backscatter): luz que vuelve */\n"
    "    float back = exp(-depth_mm * PHI_INV * max(mu_a.g, 0.001));\n"
    "    L += albedo * back * vec3(1.0, 0.72, 0.46) * 0.35;\n\n"
    "    return L;\n"
    "}\n\n"
    "/* ── ALBEDO BIOQUÍMICO — Donner-Jensen cromóforo completo ── */\n"
    "vec3 skin_bio_albedo(\n"
    "    vec3  base_tex,\n"
    "    float melanin_eu, float melanin_ph,\n"
    "    float hemoglobin_oxy, float hemoglobin_deoxy,\n"
    "    float bilirubin, float carotene,\n"
    "    float age, float sun_damage\n"
    ") {\n"
    "    vec3 c = base_tex;\n"
    "    /* Eumelanina: absorción amplia, más en azul */\n"
    "    c *= (1.0 - vec3(0.55, 0.38, 0.72) * melanin_eu);\n"
    "    /* Feomelanina: rojo-amarillo */\n"
    "    c *= (1.0 - vec3(0.05, 0.20, 0.60) * melanin_ph);\n"
    "    /* Oxihemoglobina: rosado */\n"
    "    c += vec3(0.22, 0.04, 0.02) * hemoglobin_oxy;\n"
    "    /* Deoxihemoglobina: azulado */\n"
    "    c += vec3(0.02, 0.04, 0.12) * hemoglobin_deoxy;\n"
    "    /* Bilirrubina: amarillo */\n"
    "    c += vec3(0.15, 0.12, -0.02) * bilirubin;\n"
    "    /* Caroteno: naranja */\n"
    "    c += vec3(0.18, 0.12, 0.0) * carotene;\n"
    "    /* Envejecimiento: desaturar + amarillear */\n"
    "    float lum = dot(c, vec3(0.2126, 0.7152, 0.0722));\n"
    "    c = mix(c, vec3(lum) * vec3(1.02, 1.0, 0.95), age * 0.12);\n"
    "    /* Daño solar: manchas de hiperpigmentación */\n"
    "    c *= (1.0 + sun_damage * vec3(-0.1, -0.08, -0.15));\n"
    "    return clamp(c, 0.0, 1.0);\n"
    "}\n\n"
    "/* ── POROS SEBÁCEOS — modelo Voronoi con interreflexión ── */\n"
    "/* Referencia: Ghosh et al. 2011 «Estimating Specular Roughness\n"
    " *              and Anisotropy from Second Order Irradiance Gradients»\n"
    " * Los poros crean micro-cavidades donde la luz sufre múltiple\n"
    " * reflexión antes de salir — resultado: oscurecimiento local */\n"
    "struct PoreResult {\n"
    "    float depth_mask;    /* 0=piel lisa 1=centro del poro */\n"
    "    vec3  normal_delta;  /* perturbación de normal */\n"
    "    float ao;            /* oclusión ambiental micro */\n"
    "    float roughness_mod; /* modificador de roughness */\n"
    "    float oiliness_mod;  /* sebo acumulado en borde del poro */\n"
    "};\n\n"
    "PoreResult pore_system(vec2 uv, float density, float depth,\n"
    "                        float scale, float age) {\n"
    "    PoreResult r;\n"
    "    /* Escalar UV según densidad de poros */\n"
    "    vec2 puv = uv * scale;\n"
    "    /* Voronoi — centro de la celda = ostium del poro */\n"
    "    vec3 vor = voronoi(vec3(puv, 0.));\n"
    "    float dist = vor.x;                /* distancia al poro más cercano */\n"
    "    float cell_id = vor.z;             /* identidad única del poro */\n"
    "    /* Variación de tamaño por id de celda (poros no son uniformes) */\n"
    "    float pore_r = 0.08 + 0.06 * hash11(cell_id * 7.3);\n"
    "    /* Factor de envejecimiento: poros se dilatan con la edad */\n"
    "    pore_r *= (1.0 + age * 0.4);\n"
    "    /* Perfil cónico del poro: más oscuro en el centro */\n"
    "    float inside = smoothstep(pore_r, pore_r * 0.3, dist);\n"
    "    /* Borde del poro: queratina engrosada */\n"
    "    float rim = smoothstep(pore_r * 0.3, pore_r, dist) *\n"
    "                smoothstep(pore_r * 1.2, pore_r, dist);\n"
    "    /* Normal perturbation: las paredes del poro inclinan la normal */\n"
    "    vec2 pore_center = puv - hash22(floor(puv + 0.5));\n"
    "    vec2 pore_grad   = normalize(pore_center + vec2(1e-5)) * inside * depth;\n"
    "    r.normal_delta  = vec3(pore_grad.x, pore_grad.y, 0.0) * 2.5;\n"
    "    /* Oclusión: las paredes del poro bloquean la luz incidente */\n"
    "    r.ao            = 1.0 - inside * depth * 0.7;\n"
    "    r.depth_mask    = inside;\n"
    "    /* El borde del poro acumula sebo → más brillante */\n"
    "    r.oiliness_mod  = rim * 0.3;\n"
    "    /* El fondo del poro es más rugoso */\n"
    "    r.roughness_mod = inside * 0.2 + rim * (-0.15);\n"
    "    return r;\n"
    "}\n\n"
    "/* ── PIEL VELLOSA — modelo de fibra corta ── */\n"
    "/* Vello facial: longitud 0.5-2mm, ángulo de salida ~30° */\n"
    "float peach_fuzz(vec3 N, vec3 L, vec3 V, vec2 uv,\n"
    "                  float density, float length_mm) {\n"
    "    /* Dirección aleatoria de cada fibra de vello */\n"
    "    vec3 hair_dir = normalize(vec3(\n"
    "        phi_noise(vec3(uv * 20., 0.1)) - 0.5,\n"
    "        phi_noise(vec3(uv * 20., 0.7)) - 0.5,\n"
    "        0.8 + phi_noise(vec3(uv * 20., 1.3)) * 0.2\n"
    "    ));\n"
    "    /* Tangente del pelo: T = N + desviación */\n"
    "    vec3 T = normalize(hair_dir + N * 0.5);\n"
    "    /* Kajiya-Kay diffuse para fibra */\n"
    "    float sinTL = sqrt(max(0., 1.0 - dot(T,L)*dot(T,L)));\n"
    "    float sinTV = sqrt(max(0., 1.0 - dot(T,V)*dot(T,V)));\n"
    "    /* Transmitancia a través del vello (semi-translucido) */\n"
    "    float diff = sinTL * (0.6 + 0.4 * dot(N,L));\n"
    "    /* Especular de Marschner-Kay para vello fino */\n"
    "    float spec = pow(max(0., sinTL * sinTV - dot(T,L)*dot(T,V)), 6.0);\n"
    "    float mask = density * (0.5 + 0.5 * phi_noise(vec3(uv*15., 2.1)));\n"
    "    return (diff * 0.6 + spec * 0.4) * mask * length_mm * 0.2;\n"
    "}\n\n"
    "/* ── VASCULARIZACIÓN DINÁMICA — pulso cardíaco en piel ── */\n"
    "/* El pulso cardíaco (70bpm = 1.17Hz) es visible en sienes,\n"
    " * cuello, labios. Se modela como variación periódica de\n"
    " * hemoglobina local sincronizada con heartbeat_phase */\n"
    "vec3 vascular_pulse(\n"
    "    vec3 base_color,\n"
    "    vec3 vascular_map,     /* R=arteria G=vena B=capilar */\n"
    "    float heartbeat_phase, /* 0-TAU en tiempo real */\n"
    "    float hemoglobin,\n"
    "    float skin_tone\n"
    ") {\n"
    "    /* Ciclo cardíaco: sístole rápida + diástole lenta */\n"
    "    /* Forma de onda: función de pulso asimétrico */\n"
    "    float systole  = exp(-pow(fract(heartbeat_phase/TAU)*5.0, 2.0));\n"
    "    float diastole = 1.0 - systole;\n"
    "    /* Arterias: rojo brillante durante sístole */\n"
    "    vec3 artery_pulse = vec3(0.18, 0.04, 0.02) * vascular_map.r * systole;\n"
    "    /* Venas: azul oscuro, menos variación */\n"
    "    vec3 vein_color   = vec3(0.04, 0.06, 0.20) * vascular_map.g * 0.3;\n"
    "    /* Capilares: distribucion homogénea, varían con el pulso */\n"
    "    vec3 cap_color    = vec3(0.12, 0.04, 0.03) * vascular_map.b * \n"
    "                         (0.5 + 0.5 * systole) * hemoglobin;\n"
    "    return base_color + (artery_pulse + vein_color + cap_color) * \n"
    "           (1.0 - skin_tone * 0.4);  /* visible menos en piel oscura */\n"
    "}\n\n"
    "/* ── GLÁNDULAS SUDORÍPARAS — mojado dinámico ── */\n"
    "struct SweatResult {\n"
    "    float wetness;       /* 0-1 */\n"
    "    float roughness_mod; /* mojado = menos rugoso */\n"
    "    vec3  specular_add;  /* reflexión de gota */\n"
    "    float normal_perturb;/* superficie del agua */\n"
    "};\n"
    "SweatResult sweat_system(\n"
    "    vec2 uv, float time, float sweat_level,\n"
    "    vec3 N, vec3 L, vec3 V\n"
    ") {\n"
    "    SweatResult r;\n"
    "    r.wetness = 0.0; r.roughness_mod = 0.0;\n"
    "    r.specular_add = vec3(0.); r.normal_perturb = 0.0;\n"
    "    if(sweat_level < 0.01) return r;\n"
    "    /* Distribución de glándulas eccrina por fBm */\n"
    "    float gland_map = fbm(vec3(uv*25., time*0.1), 3, 2.0, 0.5);\n"
    "    float gland_mask = smoothstep(0.5, 0.7, gland_map) * sweat_level;\n"
    "    /* Gotas individuales sobre la piel */\n"
    "    vec3 vor = voronoi(vec3(uv*30., time*0.03));\n"
    "    float drop_center = smoothstep(0.3, 0.05, vor.x) * sweat_level;\n"
    "    /* La gota tiene IOR de agua = 1.333 → especular brillante */\n"
    "    vec3 H = normalize(L + V);\n"
    "    float water_spec = pow(max(dot(N,H), 0.), 256.0) * drop_center;\n"
    "    /* Superficie de la gota: normal perturbada */\n"
    "    float wave = sin(uv.x*200.0 + time*3.0) * sin(uv.y*200.0 + time*2.5);\n"
    "    r.wetness       = gland_mask + drop_center * 0.5;\n"
    "    r.roughness_mod = -r.wetness * 0.4;   /* más húmedo = menos rugoso */\n"
    "    r.specular_add  = vec3(water_spec) * drop_center * 0.8;\n"
    "    r.normal_perturb= wave * drop_center * 0.02;\n"
    "    return r;\n"
    "}\n\n"
    "/* ── ARRUGAS DINÁMICAS — controladas por FACS ── */\n"
    "/* Las arrugas dinámicas son resultado directo de las\n"
    " * contracciones musculares. A diferencia de las estáticas\n"
    " * (líneas permanentes), estas aparecen con la expresión */\n"
    "vec3 dynamic_wrinkles(\n"
    "    vec2 uv,\n"
    "    float au1,   /* inner brow raise */\n"
    "    float au2,   /* outer brow raise */\n"
    "    float au4,   /* brow lowerer */\n"
    "    float au6,   /* cheek raiser */\n"
    "    float au12,  /* lip corner puller (sonrisa) */\n"
    "    float au25,  /* lips part (apertura labios) */\n"
    "    float age    /* arrugas estáticas = permanentes */\n"
    ") {\n"
    "    vec3 N_delta = vec3(0.);\n"
    "    /* Frente: líneas horizontales por AU1+AU2+AU4 */\n"
    "    float forehead_mask = smoothstep(0.70, 0.80, uv.y);\n"
    "    float brow_raise = max(au1, au2);\n"
    "    float horiz_lines = sin(uv.y * PI * 8.0) * brow_raise * forehead_mask;\n"
    "    float brow_lower = sin(uv.y * PI * 6.0 + uv.x*PI*3.) * au4 * forehead_mask;\n"
    "    N_delta.x += horiz_lines * 0.04 + brow_lower * 0.03;\n"
    "    /* Surco nasolabial: se profundiza con sonrisa (AU6+AU12) */\n"
    "    float naso_mask = (abs(uv.x - 0.5) < 0.12 && uv.y > 0.35 && uv.y < 0.55)\n"
    "                    ? 1.0 : 0.0;\n"
    "    float naso_smile = (au6 * 0.4 + au12 * 0.6) * naso_smile * naso_mask;\n"
    "    N_delta.y += sin(uv.x * PI * 6.0) * naso_smile * 0.05;\n"
    "    /* Patas de gallo: canthus lateral AU6 */\n"
    "    float crow_dist = length(uv - vec2(uv.x < 0.5 ? 0.2 : 0.8, 0.52));\n"
    "    float crow_feet = exp(-crow_dist * 30.0) * au6 * 0.06;\n"
    "    N_delta.x += sin(atan(uv.y - 0.52, uv.x - (uv.x<0.5?0.2:0.8)) * 6.0)\n"
    "                 * crow_feet;\n"
    "    /* Líneas estáticas con la edad */\n"
    "    float static_w = fbm(vec3(uv * 8., 1.5), 4, 2.0, 0.55) * age;\n"
    "    N_delta += vec3(static_w * 0.03, static_w * 0.02, 0.);\n"
    "    return N_delta;\n"
    "}\n\n";

/* ═══════════════════════════════════════════════════════════════
 * GLSL — SHADER PRINCIPAL DE PIEL NG
 * ═══════════════════════════════════════════════════════════════ */
static const char *NG_SKIN_FRAG_MAIN =
    "/* ══════════════════════════════════════════════════════════ */\n"
    "/* SHADER PRINCIPAL DE PIEL NEXT GENERATION                   */\n"
    "/* ══════════════════════════════════════════════════════════ */\n\n"
    "in vec3  v_pos;\n"
    "in vec3  v_normal;\n"
    "in vec3  v_tangent;\n"
    "in vec3  v_bitangent;\n"
    "in vec2  v_uv;\n"
    "in vec4  v_color;       /* melanina/SSS regional baked */\n"
    "in float v_region;      /* zona facial 0-20 */\n"
    "in vec3  v_world_pos;\n"
    "in float v_depth_mm;    /* espesor de tejido baked */\n\n"
    "out vec4 fragColor;\n\n"
    "/* ── Samplers de texturas de alta resolución ── */\n"
    "uniform sampler2D u_albedo_map;       /* 4K: color base de piel */\n"
    "uniform sampler2D u_normal_map;       /* 4K: normal map principal */\n"
    "uniform sampler2D u_pore_normal;      /* 2K: normal de poros en tile */\n"
    "uniform sampler2D u_microdetail_norm; /* 1K: micro-rugosidad superficial */\n"
    "uniform sampler2D u_roughness_map;    /* 4K: roughness + metallic */\n"
    "uniform sampler2D u_sss_map;          /* 2K: mapa de espesor SSS */\n"
    "uniform sampler2D u_vascular_map;     /* 2K: red vascular R=arteria G=vena B=cap */\n"
    "uniform sampler2D u_wrinkle_normal;   /* 2K: arrugas estáticas */\n"
    "uniform sampler2D u_makeup_layer;     /* 4K: capa de maquillaje */\n"
    "uniform sampler2D u_moisture_layer;   /* 2K: capa de humedad */\n"
    "uniform sampler2D u_ao_map;           /* 2K: ambient occlusion */\n"
    "uniform sampler2D u_translucency_map; /* 2K: translucencia regional */\n"
    "uniform samplerCube u_env_map;        /* IBL environment map */\n"
    "uniform samplerCube u_irradiance_map; /* IBL irradiance */\n\n"
    "/* ── Bioquímica ── */\n"
    "uniform float u_melanin_eu;        /* 0-1 eumelanina */\n"
    "uniform float u_melanin_ph;        /* 0-1 feomelanina */\n"
    "uniform float u_hemoglobin_oxy;    /* 0-1 oxihemoglobina */\n"
    "uniform float u_hemoglobin_deoxy;  /* 0-1 deoxihemoglobina */\n"
    "uniform float u_bilirubin;         /* 0-1 bilirrubina */\n"
    "uniform float u_carotene;          /* 0-1 caroteno */\n"
    "uniform float u_age_norm;          /* 0-1 envejecimiento */\n"
    "uniform float u_sun_damage;        /* 0-1 fotodaño */\n\n"
    "/* ── PBR ── */\n"
    "uniform float u_roughness;         /* base roughness lipídica */\n"
    "uniform float u_ior;               /* IOR piel ~ 1.4-1.55 */\n"
    "uniform float u_oiliness;          /* 0-1 grasa superficial */\n\n"
    "/* ── Poros ── */\n"
    "uniform float u_pore_density;      /* 0-1 densidad de poros */\n"
    "uniform float u_pore_depth;        /* 0-1 profundidad */\n"
    "uniform float u_pore_scale;        /* escala tile de poros */\n\n"
    "/* ── Pelo velloso ── */\n"
    "uniform float u_fuzz_density;      /* 0-1 densidad del vello */\n"
    "uniform float u_fuzz_length;       /* longitud en mm */\n"
    "uniform vec3  u_fuzz_color;        /* color del vello */\n\n"
    "/* ── Dinámica ── */\n"
    "uniform float u_heartbeat_phase;   /* fase cardíaca 0-TAU */\n"
    "uniform float u_sweat_level;       /* 0-1 sudoración */\n"
    "uniform float u_time;\n\n"
    "/* ── FACS para arrugas dinámicas ── */\n"
    "uniform float u_au1, u_au2, u_au4, u_au6, u_au12, u_au25;\n\n"
    "/* ── Luces ── */\n"
    "uniform vec3  u_light_dir_0;       /* luz principal key */\n"
    "uniform vec3  u_light_color_0;\n"
    "uniform float u_light_intensity_0;\n"
    "uniform vec3  u_light_dir_1;       /* luz de relleno fill */\n"
    "uniform vec3  u_light_color_1;\n"
    "uniform float u_light_intensity_1;\n"
    "uniform vec3  u_light_dir_2;       /* contraluz rim */\n"
    "uniform vec3  u_light_color_2;\n"
    "uniform float u_light_intensity_2;\n"
    "uniform vec3  u_view_dir;\n"
    "uniform vec3  u_camera_pos;\n"
    "uniform float u_exposure;\n\n"
    "/* ── Capas compuestas ── */\n"
    "uniform float u_makeup_blend;      /* 0-1 intensidad maquillaje */\n"
    "uniform float u_moisture_blend;    /* 0-1 lágrimas/gloss/sudor */\n"
    "uniform float u_sss_weight;        /* peso global SSS */\n\n"
    "void main() {\n"
    "    vec3  V = normalize(u_view_dir);\n"
    "    vec2  uv = v_uv;\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 1: NORMAL COMPUESTA DE ALTA RESOLUCIÓN\n"
    "     * Combina: mapa principal + poros + micro-detalle +\n"
    "     *          arrugas estáticas + arrugas dinámicas\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    /* Mapa de normal principal (baked de high-poly) */\n"
    "    vec3 nm_main = texture(u_normal_map, uv).rgb * 2.0 - 1.0;\n"
    "    /* Poros: tileados, escala 40-60x para resolución de ~0.1mm */\n"
    "    vec3 nm_pore = texture(u_pore_normal, fract(uv * u_pore_scale)).rgb * 2.0 - 1.0;\n"
    "    /* Micro-rugosidad superficial: escala 200x (queratina) */\n"
    "    vec3 nm_micro = texture(u_microdetail_norm, fract(uv * 200.0)).rgb * 2.0 - 1.0;\n"
    "    /* Arrugas estáticas */\n"
    "    vec3 nm_wrink = texture(u_wrinkle_normal, uv).rgb * 2.0 - 1.0;\n"
    "    /* Sistema de poros con AO, depth y roughness */\n"
    "    PoreResult pores = pore_system(uv, u_pore_density, u_pore_depth,\n"
    "                                    u_pore_scale, u_age_norm);\n"
    "    /* Arrugas dinámicas por FACS */\n"
    "    vec3 nm_dyn = dynamic_wrinkles(uv, u_au1, u_au2, u_au4,\n"
    "                                    u_au6, u_au12, u_au25, u_age_norm);\n"
    "    /* Normal compuesta — pesos calibrados para piel realista */\n"
    "    vec3 N_ts = normalize(\n"
    "        nm_main * 1.00\n"
    "      + nm_pore * (u_pore_depth * 3.0) + pores.normal_delta\n"
    "      + nm_micro * 0.15\n"
    "      + nm_wrink * u_age_norm * 0.5\n"
    "      + nm_dyn\n"
    "    );\n"
    "    /* Transformar de tangent-space a world-space */\n"
    "    mat3 TBN = mat3(\n"
    "        normalize(v_tangent),\n"
    "        normalize(v_bitangent),\n"
    "        normalize(v_normal));\n"
    "    vec3 N = normalize(TBN * N_ts);\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 2: ALBEDO BIOQUÍMICO COMPLETO\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    vec4 albedo_smp = texture(u_albedo_map, uv);\n"
    "    /* Colorimetría bioquímica completa */\n"
    "    vec3 albedo = skin_bio_albedo(\n"
    "        albedo_smp.rgb * v_color.rgb,\n"
    "        u_melanin_eu, u_melanin_ph,\n"
    "        u_hemoglobin_oxy, u_hemoglobin_deoxy,\n"
    "        u_bilirubin, u_carotene,\n"
    "        u_age_norm, u_sun_damage);\n"
    "    /* El oscurecimiento de los poros */\n"
    "    albedo *= (pores.ao * 0.7 + 0.3);\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 3: ROUGHNESS ADAPTATIVA MULTI-FACTOR\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    vec4 rgh_smp = texture(u_roughness_map, uv);\n"
    "    float roughness = u_roughness * rgh_smp.r;\n"
    "    /* Poros: el borde es más brillante (sebo), el centro más rugoso */\n"
    "    roughness += pores.roughness_mod;\n"
    "    /* Oleosidad: reduce roughness en zonas T (frente, nariz, mentón) */\n"
    "    roughness = mix(roughness, roughness * PHI_INV, u_oiliness);\n"
    "    roughness = clamp(roughness, 0.02, 0.98);\n"
    "    float alpha = roughness * roughness; /* perceptual roughness → linear */\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 4: SISTEMA DE PIEL VELLOSA (PEACH FUZZ)\n"
    "     * Añade la contribución del vello facial fino\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    vec3  L0  = normalize(u_light_dir_0);\n"
    "    float fuzz_contrib = peach_fuzz(N, L0, V, uv,\n"
    "                                     u_fuzz_density, u_fuzz_length);\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 5: SSS 8-CAPA ESPECTRAL\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    float thickness   = texture(u_sss_map, uv).r * v_depth_mm * 0.25;\n"
    "    float translucency= texture(u_translucency_map, uv).r;\n"
    "    vec3 sss_color = sss_8layer(\n"
    "        albedo, thickness,\n"
    "        u_melanin_eu, u_melanin_ph,\n"
    "        u_hemoglobin_oxy, u_hemoglobin_deoxy,\n"
    "        u_bilirubin, u_carotene, u_age_norm);\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 6: VASCULARIZACIÓN DINÁMICA CON PULSO\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    vec3 vasc_map = texture(u_vascular_map, uv).rgb;\n"
    "    vec3 albedo_vasc = vascular_pulse(\n"
    "        albedo, vasc_map,\n"
    "        u_heartbeat_phase,\n"
    "        u_hemoglobin_oxy + u_hemoglobin_deoxy,\n"
    "        u_melanin_eu);\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 7: BRDF PBR COOK-TORRANCE — 3 LUCES\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    /* IOR de piel → F0 */\n"
    "    float F0_s = pow((1.0 - u_ior) / (1.0 + u_ior), 2.0);\n"
    "    vec3  F0   = vec3(F0_s); /* dielectrico */\n"
    "    vec3  F82  = albedo * 0.1; /* F82: pequeña contribucion de color */\n\n"
    "    vec3 direct = vec3(0.);\n"
    "    /* Evaluar 3 luces */\n"
    "    for(int li = 0; li < 3; li++) {\n"
    "        vec3 L, Lc; float Li;\n"
    "        if(li == 0) { L=normalize(u_light_dir_0); Lc=u_light_color_0; Li=u_light_intensity_0; }\n"
    "        else if(li==1) { L=normalize(u_light_dir_1); Lc=u_light_color_1; Li=u_light_intensity_1; }\n"
    "        else   { L=normalize(u_light_dir_2); Lc=u_light_color_2; Li=u_light_intensity_2; }\n"
    "        vec3 H = normalize(V + L);\n"
    "        float NdL = max(dot(N, L), 0.0);\n"
    "        float NdV = max(dot(N, V), 1e-4);\n"
    "        float NdH = max(dot(N, H), 0.0);\n"
    "        float VdH = max(dot(V, H), 0.0);\n"
    "        vec3  F = F_Schlick(VdH, F0, F82);\n"
    "        float D = D_GGX(NdH, alpha);\n"
    "        float G = G_Smith(NdV, NdL, roughness);\n"
    "        vec3  spec = (D * G * F) / max(4.0 * NdV * NdL, 1e-7);\n"
    "        vec3  kD   = (1.0 - F);\n"
    "        vec3  diff = kD * albedo_vasc * INV_PI;\n"
    "        /* Vello: contribución difusa anisotrópica */\n"
    "        diff += u_fuzz_color * fuzz_contrib * kD * u_fuzz_density;\n"
    "        direct += (diff + spec) * NdL * Lc * Li;\n"
    "    }\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 8: ILUMINACIÓN AMBIENTE (IBL)\n"
    "     * Image-Based Lighting para reflexiones en piel\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    vec3 R = reflect(-V, N);\n"
    "    /* Irradiancia difusa del env (piel + SSS) */\n"
    "    vec3 irradiance = texture(u_irradiance_map, N).rgb;\n"
    "    /* Reflexión especular del env (poros brillantes, zona T) */\n"
    "    float mip_level = roughness * 8.0;  /* 0=liso 8=muy rugoso */\n"
    "    vec3 env_spec = textureLod(u_env_map, R, mip_level).rgb;\n"
    "    /* BRDF split-sum aproximación para IBL */\n"
    "    float NdV = max(dot(N, V), 0.);\n"
    "    vec2  brdf_lut = vec2(max(0., 1.0 - roughness), NdV); /* simplificado */\n"
    "    vec3  F_ibl = F_Schlick(NdV, F0, F82);\n"
    "    vec3  kD_ibl= (1.0 - F_ibl);\n"
    "    float ao = texture(u_ao_map, uv).r * pores.ao;\n"
    "    vec3  ambient_diff = kD_ibl * albedo_vasc * irradiance * ao;\n"
    "    vec3  ambient_spec = env_spec * F_ibl * (1.0 - roughness * 0.5) * ao;\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 9: COMPOSICION FINAL\n"
    "     * Direct + SSS + IBL + maquillaje + humedad\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    vec3 color = direct + ambient_diff + ambient_spec;\n"
    "    /* SSS: añadir debajo de la superficie */\n"
    "    color += sss_color * u_sss_weight * 0.45;\n"
    "    /* Sudoración */\n"
    "    SweatResult sw = sweat_system(uv, u_time, u_sweat_level, N, L0, V);\n"
    "    color = mix(color, color * (1.0 + sw.wetness * 0.2), sw.wetness);\n"
    "    color += sw.specular_add;\n"
    "    roughness = clamp(roughness + sw.roughness_mod, 0.01, 1.0);\n"
    "    /* Maquillaje */\n"
    "    vec4 makeup = texture(u_makeup_layer, uv);\n"
    "    color = mix(color, makeup.rgb + color * 0.1, makeup.a * u_makeup_blend);\n"
    "    /* Humedad (lágrimas, gloss, lluvia) */\n"
    "    vec4 moist = texture(u_moisture_layer, uv);\n"
    "    color += moist.rgb * moist.a * u_moisture_blend;\n\n"
    "    /* ═════════════════════════════════════════════════════\n"
    "     * PASO 10: TONE MAPPING + CORRECCIÓN DE COLOR\n"
    "     * ═════════════════════════════════════════════════════ */\n"
    "    color *= u_exposure;\n"
    "    color  = ACES_tonemap(color);\n"
    "    /* Corrección gamma 2.2 → sRGB */\n"
    "    color  = pow(clamp(color, 0.0, 1.0), vec3(1.0 / 2.2));\n"
    "    fragColor = vec4(color, 1.0);\n"
    "}\n";

/* ═══════════════════════════════════════════════════════════════
 * rig_face_ng_skin_shader() — Función principal de generación
 * ═══════════════════════════════════════════════════════════════ */
int rig_face_ng_skin_shader(const RigFaceNGSkinCtx *ctx, RigArtResultNG *out)
{
    if (!ctx || !out) return -1;

    char *frag = (char*)rl_malloc(SKIN_BUF);
    char *vert = (char*)rl_malloc(SKIN_BUF / 2);
    char *js   = (char*)rl_malloc(JS_BUF);
    if (!frag || !vert || !js) {
        rl_free(frag); rl_free(vert); rl_free(js);
        return -1;
    }

    int fp = 0, vp = 0, jp = 0;
    int fsz = SKIN_BUF, vsz = SKIN_BUF/2, jsz = JS_BUF;

    /* ── VERTEX SHADER NG ── */
    FA(vert, vsz, vp, "%s", NG_GLSL_HEADER);
    FA(vert, vsz, vp,
        "/* RigCom NG Skin — Vertex Shader */\n"
        "in vec3  a_pos;\n"
        "in vec3  a_normal;\n"
        "in vec3  a_tangent;\n"
        "in vec2  a_uv;\n"
        "in vec4  a_color;      /* melanina regional baked */\n"
        "in float a_region;     /* zona facial */\n"
        "in float a_depth_mm;   /* espesor de tejido en mm */\n"
        "in vec4  a_bone_ids;\n"
        "in vec4  a_bone_w;\n\n"
        "/* FACS morph texture: 128 targets × 1 columna por vértice */\n"
        "uniform highp sampler2D u_morph_tex;\n"
        "uniform float u_morph_w[128];     /* pesos de los 128 FACS */\n"
        "uniform int   u_morph_count;      /* FACS activos (optimización) */\n\n"
        "/* Dual-quaternion skinning — 23 huesos faciales */\n"
        "uniform vec4  u_dq_real[23];      /* parte real del DQ */\n"
        "uniform vec4  u_dq_dual[23];      /* parte dual del DQ */\n\n"
        "uniform mat4  u_mvp;\n"
        "uniform mat4  u_model;\n"
        "uniform mat3  u_normal_mat;\n"
        "uniform float u_time;\n"
        "uniform float u_age_norm;        /* deformación gravitacional */\n"
        "uniform float u_jaw_open;        /* mandíbula */\n"
        "uniform float u_breathing;       /* ciclo respiratorio 0-1 */\n\n"
        "out vec3  v_pos;\n"
        "out vec3  v_normal;\n"
        "out vec3  v_tangent;\n"
        "out vec3  v_bitangent;\n"
        "out vec2  v_uv;\n"
        "out vec4  v_color;\n"
        "out float v_region;\n"
        "out vec3  v_world_pos;\n"
        "out float v_depth_mm;\n\n"
        "/* Dual Quaternion blend */\n"
        "void dq_blend(in vec4 bids, in vec4 bw,\n"
        "               out vec4 qr, out vec4 qd) {\n"
        "    qr = vec4(0.); qd = vec4(0.);\n"
        "    float pivot = dot(u_dq_real[int(bids.x)], u_dq_real[int(bids.x)]);\n"
        "    for(int k=0;k<4;k++) {\n"
        "        int bi = int(k==0?bids.x:k==1?bids.y:k==2?bids.z:bids.w);\n"
        "        float bw_k = (k==0?bw.x:k==1?bw.y:k==2?bw.z:bw.w);\n"
        "        if(bw_k < 0.001) continue;\n"
        "        float s = sign(dot(u_dq_real[bi], qr));\n"
        "        if(length(qr)<0.001) s=1.;\n"
        "        qr += s * bw_k * u_dq_real[bi];\n"
        "        qd += s * bw_k * u_dq_dual[bi];\n"
        "    }\n"
        "    float len = length(qr);\n"
        "    if(len > 0.001) { qr /= len; qd /= len; }\n"
        "}\n\n"
        "vec3 dq_transform(vec4 qr, vec4 qd, vec3 p) {\n"
        "    /* Rotación */\n"
        "    vec3 t = 2.0 * cross(qr.xyz, p) + 2.0*qr.w*p;\n"
        "    vec3 rot_p = p + cross(qr.xyz, t);\n"
        "    /* Traslación */\n"
        "    vec3 trans = 2.0*(qr.w*qd.xyz - qd.w*qr.xyz + cross(qr.xyz,qd.xyz));\n"
        "    return rot_p + trans;\n"
        "}\n\n"
        "void main() {\n"
        "    vec3 pos = a_pos;\n"
        "    vec3 nrm = a_normal;\n\n"
        "    /* ── 1. Aplicar FACS morphs desde textura ── */\n"
        "    int active = min(u_morph_count, 128);\n"
        "    for(int i = 0; i < 128; i++) {\n"
        "        if(i >= active) break;\n"
        "        float w = u_morph_w[i];\n"
        "        if(w < 0.001) continue;\n"
        "        vec2 tex_c = vec2((float(i) + 0.5) / 128.0, a_uv.y);\n"
        "        vec4 delta = texture(u_morph_tex, tex_c);\n"
        "        /* delta.xyz = desplazamiento de posición en [-1,1] */\n"
        "        pos += (delta.xyz * 2.0 - 1.0) * w * 0.015;\n"
        "        /* delta.w = desplazamiento de normal */\n"
        "    }\n\n"
        "    /* ── 2. Deformación de edad: caída gravitacional ── */\n"
        "    if(pos.y < 0.0) {\n"
        "        float sag = u_age_norm * 0.025;\n"
        "        pos.y -= abs(pos.y) * sag;\n"
        "        /* Jowl: tejido de mandíbula cae hacia adelante */\n"
        "        if(abs(pos.x) > 0.04 && pos.y < -0.02)\n"
        "            pos.z -= abs(pos.y) * u_age_norm * 0.01;\n"
        "    }\n"
        "    /* Ptosis orbital: párpados superiores caen con la edad */\n"
        "    if(pos.y > 0.01 && pos.y < 0.04 && abs(pos.x) > 0.01)\n"
        "        pos.y -= u_age_norm * 0.003;\n\n"
        "    /* ── 3. Respiración: expansión de narinas + elevación ── */\n"
        "    /* Las narinas se abren ligeramente durante la inspiración */\n"
        "    if(v_region > 4.5 && v_region < 5.5) {  /* región nariz */\n"
        "        pos.x *= (1.0 + u_breathing * 0.04);\n"
        "    }\n"
        "    /* El pecho sube levemente (visible en el cuello) */\n"
        "    if(v_region > 18.5) {  /* cuello */\n"
        "        pos.y += u_breathing * 0.003;\n"
        "    }\n\n"
        "    /* ── 4. Dual-Quaternion Skinning ── */\n"
        "    vec4 qr, qd;\n"
        "    dq_blend(a_bone_ids, a_bone_w, qr, qd);\n"
        "    pos = dq_transform(qr, qd, pos);\n"
        "    nrm = normalize(dq_transform(qr, vec4(0.), nrm));\n\n"
        "    /* ── 5. Outputs ── */\n"
        "    vec4 world = u_model * vec4(pos, 1.0);\n"
        "    v_world_pos = world.xyz;\n"
        "    v_pos       = (u_model * vec4(pos, 1.0)).xyz;\n"
        "    v_normal    = normalize(u_normal_mat * nrm);\n"
        "    v_tangent   = normalize(u_normal_mat * a_tangent);\n"
        "    v_bitangent = cross(v_normal, v_tangent);\n"
        "    v_uv        = a_uv;\n"
        "    v_color     = a_color;\n"
        "    v_region    = a_region;\n"
        "    v_depth_mm  = a_depth_mm;\n"
        "    gl_Position = u_mvp * vec4(pos, 1.0);\n"
        "}\n");

    /* ── FRAGMENT SHADER COMPLETO ── */
    FA(frag, fsz, fp, "%s", NG_GLSL_HEADER);
    FA(frag, fsz, fp, "%s", NG_GLSL_PROCEDURAL);
    FA(frag, fsz, fp, "%s", NG_GLSL_PBR_SSS);
    FA(frag, fsz, fp, "%s", NG_SKIN_FRAG_MAIN);

    /* ── JAVASCRIPT RUNTIME — WebGL2 setup completo ── */
    FA(js, jsz, jp,
        "// §NG-SKIN RigCom Next Generation — Skin Runtime\n"
        "// φ=%.16f · Richard Felipe Urbina\n"
        "'use strict';\n\n"
        "class RigNGSkinMaterial {\n"
        "  constructor(gl, prog) {\n"
        "    this.gl = gl;\n"
        "    this.prog = prog;\n"
        "    this.L = n => gl.getUniformLocation(prog, n);\n"
        "    // Bioquímica inicial (adulto joven estándar)\n"
        "    this.bio = {\n"
        "      melanin_eu:       %.4f,  // eumelanina\n"
        "      melanin_ph:       %.4f,  // feomelanina\n"
        "      hemoglobin_oxy:   %.4f,  // oxihemoglobina\n"
        "      hemoglobin_deoxy: %.4f,  // deoxihemoglobina\n"
        "      bilirubin:        %.4f,  // bilirrubina\n"
        "      carotene:         %.4f,  // caroteno\n"
        "      age_norm:         %.4f,  // envejecimiento\n"
        "      sun_damage:       %.4f   // fotodaño\n"
        "    };\n"
        "    this.pbr = {\n"
        "      roughness: %.4f,\n"
        "      ior:       %.4f,\n"
        "      oiliness:  %.4f\n"
        "    };\n"
        "    this.pores = {\n"
        "      density: %.4f,\n"
        "      depth:   %.4f,\n"
        "      scale:   %.1f\n"
        "    };\n"
        "    this.fuzz = {\n"
        "      density: %.4f,\n"
        "      length:  %.4f,\n"
        "      color:   new Float32Array([%.4f, %.4f, %.4f])\n"
        "    };\n"
        "    this.dynamic = {\n"
        "      heartbeat_bpm:    70.0,\n"
        "      heartbeat_phase:  0.0,\n"
        "      sweat_level:      0.0,\n"
        "      time:             0.0\n"
        "    };\n"
        "    this.facs = new Float32Array(128);\n"
        "    this.makeup_blend   = 0.0;\n"
        "    this.moisture_blend = 0.0;\n"
        "    this.sss_weight     = %.4f;\n"
        "    this.exposure       = 1.0;\n"
        "    this.textures       = {};\n"
        "  }\n\n",
        (double)NG_PHI,
        ctx->melanin_eu, ctx->melanin_ph,
        ctx->hemoglobin_oxy, ctx->hemoglobin_deoxy,
        ctx->bilirubin, ctx->carotene,
        ctx->age_norm, ctx->sun_damage,
        ctx->roughness, ctx->ior, ctx->oiliness,
        ctx->pore_density, ctx->pore_depth, ctx->pore_scale,
        ctx->fuzz_density, ctx->fuzz_length,
        ctx->fuzz_color.x, ctx->fuzz_color.y, ctx->fuzz_color.z,
        ctx->sss_weight);

    FA(js, jsz, jp,
        "  update(dt) {\n"
        "    const d = this.dynamic;\n"
        "    d.time += dt;\n"
        "    // Pulsación cardíaca: 70bpm = 1.167Hz = TAU/0.857s\n"
        "    d.heartbeat_phase += dt * (d.heartbeat_bpm / 60.0) * Math.PI * 2.0;\n"
        "    if(d.heartbeat_phase > Math.PI * 2.0)\n"
        "      d.heartbeat_phase -= Math.PI * 2.0;\n"
        "  }\n\n"
        "  bind() {\n"
        "    const {gl, L, bio, pbr, pores, fuzz, dynamic, facs} = this;\n"
        "    // Bioquímica\n"
        "    gl.uniform1f(L('u_melanin_eu'),       bio.melanin_eu);\n"
        "    gl.uniform1f(L('u_melanin_ph'),       bio.melanin_ph);\n"
        "    gl.uniform1f(L('u_hemoglobin_oxy'),   bio.hemoglobin_oxy);\n"
        "    gl.uniform1f(L('u_hemoglobin_deoxy'), bio.hemoglobin_deoxy);\n"
        "    gl.uniform1f(L('u_bilirubin'),        bio.bilirubin);\n"
        "    gl.uniform1f(L('u_carotene'),         bio.carotene);\n"
        "    gl.uniform1f(L('u_age_norm'),         bio.age_norm);\n"
        "    gl.uniform1f(L('u_sun_damage'),       bio.sun_damage);\n"
        "    // PBR\n"
        "    gl.uniform1f(L('u_roughness'),        pbr.roughness);\n"
        "    gl.uniform1f(L('u_ior'),              pbr.ior);\n"
        "    gl.uniform1f(L('u_oiliness'),         pbr.oiliness);\n"
        "    // Poros\n"
        "    gl.uniform1f(L('u_pore_density'),     pores.density);\n"
        "    gl.uniform1f(L('u_pore_depth'),       pores.depth);\n"
        "    gl.uniform1f(L('u_pore_scale'),       pores.scale);\n"
        "    // Vello\n"
        "    gl.uniform1f(L('u_fuzz_density'),     fuzz.density);\n"
        "    gl.uniform1f(L('u_fuzz_length'),      fuzz.length);\n"
        "    gl.uniform3fv(L('u_fuzz_color'),      fuzz.color);\n"
        "    // Dinámica\n"
        "    gl.uniform1f(L('u_heartbeat_phase'), dynamic.heartbeat_phase);\n"
        "    gl.uniform1f(L('u_sweat_level'),     dynamic.sweat_level);\n"
        "    gl.uniform1f(L('u_time'),            dynamic.time);\n"
        "    // FACS para arrugas dinámicas\n"
        "    gl.uniform1f(L('u_au1'),  facs[0]);   // Inner brow raise\n"
        "    gl.uniform1f(L('u_au2'),  facs[1]);   // Outer brow raise\n"
        "    gl.uniform1f(L('u_au4'),  facs[3]);   // Brow lowerer\n"
        "    gl.uniform1f(L('u_au6'),  facs[5]);   // Cheek raiser\n"
        "    gl.uniform1f(L('u_au12'), facs[11]);  // Lip corner puller\n"
        "    gl.uniform1f(L('u_au25'), facs[24]);  // Lips part\n"
        "    // Capas\n"
        "    gl.uniform1f(L('u_makeup_blend'),   this.makeup_blend);\n"
        "    gl.uniform1f(L('u_moisture_blend'), this.moisture_blend);\n"
        "    gl.uniform1f(L('u_sss_weight'),     this.sss_weight);\n"
        "    gl.uniform1f(L('u_exposure'),       this.exposure);\n"
        "  }\n\n"
        "  // ── API pública ──\n"
        "  setEthnicity(profile) {\n"
        "    // profile = { melanin_eu, melanin_ph, hemoglobin_oxy,\n"
        "    //             hemoglobin_deoxy, bilirubin, carotene }\n"
        "    Object.assign(this.bio, profile);\n"
        "  }\n"
        "  setAge(years) {\n"
        "    this.bio.age_norm = Math.max(0, Math.min(1, years/100));\n"
        "    // Ajustes automáticos por edad\n"
        "    this.pbr.roughness = 0.45 + this.bio.age_norm * 0.25;\n"
        "    this.pbr.oiliness  = 0.3  - this.bio.age_norm * 0.15;\n"
        "    this.pores.depth   = 0.25 + this.bio.age_norm * 0.35;\n"
        "    this.sss_weight    = 0.45 - this.bio.age_norm * 0.10;\n"
        "  }\n"
        "  setHeartRate(bpm) { this.dynamic.heartbeat_bpm = bpm; }\n"
        "  setSweat(level)   { this.dynamic.sweat_level   = Math.max(0,Math.min(1,level)); }\n"
        "  setFACS(weights)  { this.facs.set(weights.slice(0,128)); }\n"
        "}\n\n"
        "// Presets de etnología biofísica\n"
        "const RIG_SKIN_PRESETS = {\n"
        "  nordic:       { melanin_eu:0.05, melanin_ph:0.08, hemoglobin_oxy:0.48, hemoglobin_deoxy:0.05, bilirubin:0.02, carotene:0.06 },\n"
        "  med_european: { melanin_eu:0.22, melanin_ph:0.12, hemoglobin_oxy:0.46, hemoglobin_deoxy:0.05, bilirubin:0.03, carotene:0.08 },\n"
        "  east_asian:   { melanin_eu:0.20, melanin_ph:0.10, hemoglobin_oxy:0.38, hemoglobin_deoxy:0.04, bilirubin:0.05, carotene:0.15 },\n"
        "  south_asian:  { melanin_eu:0.40, melanin_ph:0.08, hemoglobin_oxy:0.44, hemoglobin_deoxy:0.05, bilirubin:0.03, carotene:0.10 },\n"
        "  west_african: { melanin_eu:0.82, melanin_ph:0.04, hemoglobin_oxy:0.52, hemoglobin_deoxy:0.06, bilirubin:0.02, carotene:0.05 },\n"
        "  east_african: { melanin_eu:0.70, melanin_ph:0.06, hemoglobin_oxy:0.48, hemoglobin_deoxy:0.05, bilirubin:0.02, carotene:0.06 },\n"
        "  middle_east:  { melanin_eu:0.35, melanin_ph:0.10, hemoglobin_oxy:0.46, hemoglobin_deoxy:0.05, bilirubin:0.03, carotene:0.12 },\n"
        "  latin_am:     { melanin_eu:0.30, melanin_ph:0.10, hemoglobin_oxy:0.44, hemoglobin_deoxy:0.05, bilirubin:0.03, carotene:0.12 },\n"
        "  albinism:     { melanin_eu:0.00, melanin_ph:0.00, hemoglobin_oxy:0.78, hemoglobin_deoxy:0.08, bilirubin:0.02, carotene:0.02 },\n"
        "  jaundice:     { melanin_eu:0.20, melanin_ph:0.05, hemoglobin_oxy:0.35, hemoglobin_deoxy:0.10, bilirubin:0.85, carotene:0.08 },\n"
        "  cyanosis:     { melanin_eu:0.20, melanin_ph:0.05, hemoglobin_oxy:0.10, hemoglobin_deoxy:0.80, bilirubin:0.02, carotene:0.05 }\n"
        "};\n\n"
        "export { RigNGSkinMaterial, RIG_SKIN_PRESETS };\n");

    out->glsl_vert = vert;
    out->glsl_frag = frag;
    out->js        = js;
    out->ok        = true;
    out->phi_ratio = NG_PHI;
    out->certeza   = NG_PHI_INV;

    return fp + vp + jp;
}
